"""Guards against aigis.__version__ drifting from pyproject.toml.

This exact drift happened across the v2.0.0 and v2.0.1 releases:
__version__ stayed "1.2.0" (last touched in the v1.2.0 release, #228) while
pyproject.toml moved to "2.0.1". Nothing failed, because nothing compared
them — the stale string surfaced in generated trust-pack output instead
(CLI --version, the pack's "Aigis vX.Y.Z" line, and the policy YAML's
"Generated by" comment).
"""

from __future__ import annotations

import tomllib
from pathlib import Path

from aigis import __version__


def test_dunder_version_matches_pyproject() -> None:
    pyproject = Path(__file__).resolve().parent.parent / "pyproject.toml"
    data = tomllib.loads(pyproject.read_text(encoding="utf-8"))
    assert __version__ == data["project"]["version"]
