name: ClusterFuzzLite batch fuzzing

on:
  schedule:
    - cron: '0 13 * * *'   # daily at 13:00 UTC
  workflow_dispatch:

permissions: read-all

jobs:
  BatchFuzzing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sanitizer: [address, undefined]
    steps:
      - name: Build Fuzzers (${{ matrix.sanitizer }})
        uses: google/clusterfuzzlite/actions/build_fuzzers@52ecc61cb587ee99c26825a112a21abf19c7448c # main 2026-05
        with:
          language: python
          sanitizer: ${{ matrix.sanitizer }}

      - name: Run Fuzzers (${{ matrix.sanitizer }})
        uses: google/clusterfuzzlite/actions/run_fuzzers@52ecc61cb587ee99c26825a112a21abf19c7448c # main 2026-05
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 1800
          mode: 'batch'
          sanitizer: ${{ matrix.sanitizer }}
